# Generated by Django 4.1.5 on 2023-02-04 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_delete_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCheckout',
            fields=[
                ('purchaseBy', models.CharField(blank=True, max_length=200, null=True)),
                ('dateofpurchase', models.DateTimeField(blank=True, null=True)),
                ('purchasePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order')),
            ],
        ),
    ]
