# Generated by Django 4.1.5 on 2023-02-04 06:10

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ordercheckout'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercheckout',
            name='purchasedGame',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
    ]
