# Generated by Django 4.1.5 on 2023-02-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_dateofpurchase_ordercheckout_dateofpurchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliveredAt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isDelivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paidAt',
        ),
    ]
