# Generated by Django 4.1.5 on 2023-02-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_order_deliveredat_remove_order_isdelivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lyrics',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
