# Generated by Django 4.1.5 on 2023-03-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_remove_product_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='download',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
