# Generated by Django 4.1.5 on 2023-03-18 03:47

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_product_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download',
            field=models.FileField(blank=True, null=True, upload_to=base.models.upload_image_path),
        ),
    ]
