# Generated by Django 3.1.4 on 2023-03-25 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20230325_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
